### ISSUE TITLE
MidiKeys is not happy with Big Sur

### ISSUE THREAD

**Issue by curieux88** [flit/MidiKeys#10]
it crashes immediately. does anyone have any similar issue?

**Comment by flit** [comment]
Thanks a lot for the report! I hadn't installed macOS 11 yet due to concerns about privacy, but I'll get it set up in a VM so I can test MidiKeys.

**Comment by richardthornton** [comment]
I upgraded over the weekend and found the same trouble. Crashes immediately on launch. I have attached the Problem Report - hope it helps!

[MidiKeysReport.txt](https://github.com/flit/MidiKeys/files/5543098/MidiKeysReport.txt)

**Comment by bradhowes** [comment]
I've created two pull requests that solve the issue for me:

* #11 solves a crash in CTGradient by using NSGradient to do the same work
* #12 solves a startup issue due to unsigned libraries being loaded

I think the first should be fine to merge, but the second one is a hack just to get the app to run. It really needs someone to find the right magic settings. I don't need the shortcut functionality so I'm content with the result for now.

**Comment by flit** [comment]
Now, how to release a build for Big Sur is a difficult question given that patch #12 removes Sparkle… If I release v1.9.1 for pre-Big Sur OS versions, then it will disable future software updates for folks not moving to Big Sur. Otoh, users who _are_ going to move to Big Sur won't see that an update is available prior to moving. Sparkle supports updates that are available only on a given OS version—but since MidiKeys doesn't run at all on Big Sur that's not any help. ☹️ 

For now my plan is to just make a Big Sur-enabled v1.9.1a1 available via the GitHub project. Then hopefully I can get a full fix in place before long.

Thanks again @bradhowes for helping out!

**Comment by danikgan** [comment]
Could you kindly release v1.9.1a1?

**Comment by mattingalls** [comment]
+1!  i tried compiling it myself but i am having problems getting the submodule

**Comment by bradhowes** [comment]
I just tried compiling and running without a problem:

```
% git clone https://github.com/flit/MidiKeys.git
% cd MidiKeys
% xcodebuild -allowProvisioningUpdates DEVELOPMENT_TEAM="UP********E" -scheme "MidiKeys" build
% open DerivedData/MidiKeys/Build/Products/Debug/MidiKeys.app
```

DEVELOPMENT_TEAM needs to be set to your own value -- best done in Xcode. I just did the above to show that I was able to get a build without issue.

@mattingalls What issue did you have?

**Comment by bradhowes** [comment]
Bah! I tried again and this time I got your issue @mattingalls. This does the build:
```
% git clone https://github.com/flit/MidiKeys.git
% cd MidiKeys
% git submodule init
% git submodule update
% xcodebuild -workspace MidiKeys.xcworkspace -allowProvisioningUpdates DEVELOPMENT_TEAM="UP6SS5ES7E" -scheme "MidiKeys"
% open DerivedData/MidiKeys/Build/Products/Debug/MidiKeys.app
```
So you were missing the `git` commands after installing. Still perplexed why my earlier attempt worked. I must have not really deleted MidiKeys directory when I thought I did before cloning.

**Comment by bradhowes** [comment]
I've uploaded the build I made with the above - https://github.com/bradhowes/MidiKeys/releases/tag/v1.9.1-bh

**Comment by flit** [comment]
Here's the "official" version 1.9.1a1 notarized release:
https://github.com/flit/MidiKeys/releases/tag/v1.9.1a1

Apologies I hadn't released the build yet!

**Comment by flit** [comment]
Finally got out the final 1.9.1 release with Sparkle and ShortcutRecorder integrated. This version is now universal for x86_64 and AArch64, tested on my MacBook Air M1 and other systems. There are some additional issues I'm sure everyone has also noticed on Big Sur, for which issues have been created. Thanks again @bradhowes for helping out so quickly!
